### ISSUE TITLE
Library use with Razor Pages

### ISSUE THREAD

**Issue by travisDent** [adliance/Storyblok#15]
It appears that the library is for use MVC. Is anyone aware of getting it to work with Razor Views, or have any advice for forking the library for use with Razor Views?

**Comment by saxx** [comment]
Hey @travisDent! The "ready to use" ViewComponents and middleware are mainly for MVC, but you can use the component model (deserialisation of the Storyblok JSON responses to C# models) in Razor Views as well. You can achieve this by using the `StoryblokClient` directly, like so: https://github.com/adliance/Storyblok/blob/master/test/Adliance.Storyblok.Tests/Clients/StoryblokStoryClientTest.cs

**Comment by travisDent** [comment]
Thanks, I'll take a look.
