### ISSUE TITLE
[Request, Issue] Update SDK to add Blazor support

### ISSUE THREAD

**Issue by mhagendoorn-9292** [adliance/Storyblok#6]
Hi,

I'm currently trying to implement the C# SDK. However, because the SDK is not built to be used with Blazor, this is currently not possible.
For instance, when you follow the tutorial on the Storyblok website, you need to add a `Teaser` class. With Blazor, this works like this:

```csharp
[StoryblokComponent("teaser")]
public partial class Teaser : StoryblokComponent
{
    [JsonPropertyName("headline")]
    public string Headline { get; set; }
}
```

The problem this throws is the fact that every component in Blazor needs to have some overrides (which can found in  `ComponentBase`). Since C# doesn't allow for multiple inheritance, it's not possible to use the SDK with Blazor. Are you planning on adding Blazor support anytime soon?

Thanks!

**Comment by saxx** [comment]
Thanks for your request @mhagendoorn-9292. I was not aware of this issue in combination with Blazer (I'm not familiar with Blazor), so there are no concrete plans the add Blazer support anytime soon.

But you request got me thinking. On the top of my head I could think of two possible workarounds:

**1. Remove the inheritance in our SDK**. 
And replace it with an interface. I think this should work quite quite okay, but this will definitely break compabibility with existing clients of the SDK. Maybe keep the `StoryblokComponent` implementation for backwards compatibility, but add the possibility to "just" use an interface `IStoryblokComponent`? Would you be willing to look into it and create a PR?

**2. Don't make the StoryblokComponent the root of your Blazer Component**
Use something like this in your Blazer App (I assume this would work, I'm not that familiar with Blazer):
````
public class MyBlazorComponent : ComponentBase {
    public MyStoryblokComponent Story { get; set; }
}

public class MyStoryblokComponent Story : StoryblokComponent {
 ...
}
````
What do you think? Would this work?

**Comment by mhagendoorn-9292** [comment]
Hi @saxx! Thanks for your reply :)

The solution in itself is really quite simple. When I change `StoryblokComponent.cs` to
```csharp
public class StoryblokComponent : ComponentBase
```
The whole project builds and starts up correctly. Yay! 

The next problem, however, is in `StoryblokMiddleware.cs`. on line 180. On this line, the following method is called:
```csharp
await WriteResultAsync(context, result);
```
When this method is called, it goes through that method without any problems, until the last line of the method:
```csharp
return executor.ExecuteAsync(actionContext, result);
```

This method is trying to render all of the StoryblokComponents that it can find. When using Blazor this fails, because it's looking for `.cshtml` files, which Blazor doesn't use. Blazor uses Razor components (`.razor` files), so startup is halted with exceptions:

`
InvalidOperationException: The view 'Page' was not found.The following locations were searched: /Views/Page.cshtml /Views/Shared/Page.cshtml /Pages/Shared/Page.cshtml`.

I have no idea how I should fix this without rewriting the entire SDK. Maybe I'm overlooking something, but I'm a bit lost. Do you have any suggestions? Thanks!

**Comment by saxx** [comment]
Thank you for the detailed feedback and teaching me the Blazer specifics that I did not know before :)

So it seems that my original idea that we could update the SDK to support both MVC and Blazor in a single "one" SDK version will not work, as we don't have a `Page` that is so central to the current implementation of the SDK. We will need a second version of the SDK specifically for Blazor :(

That being said, you should be able to reuse the existing functionality for manually loading stories from Storyblok? It's not as nicely plug-and-play as the MVC integration, but the actual API communication with Storyblok (including mapping to concrete types) is quite separate from the MVC middleware integration. Please see https://github.com/adliance/Storyblok/blob/master/test/Adliance.Storyblok.Tests/Clients/StoryblokStoryClientTest.cs for examples on how to call Storyblok API, but without all the middleware that is used to automatically wire up the views.

Would this help?

**Comment by mhagendoorn-9292** [comment]
@saxx Hi, thanks for your response. It's a pity that it's not possible to use this SDK with Blazor. I can manually implement the API with no problem, but the SDK was really a nice implementation. I'll try and tinker some more, maybe there's a easy way to add Blazor support, but I'm not very hopeful :(

Thanks for taking the time to response though, it's really appreciated!

**Comment by saxx** [comment]
I'll be very happy to take a PR and publish an updated (or second) NuGet package, if you manage to add Blazor support. It's just that I don't feel very qualified to add a nice Blazor SDK, because I'm not familiar with Blazor and I don't feel that I can provide a good solution that feels "nice and plug-and-play" for or "native" to Blazor :/

**Comment by mhagendoorn-9292** [comment]
Hi @saxx! I've spent a few hours trying to make the Blazor SDK work, but had no luck. We have since decided that Blazor isn't as mature as we would like, so we've converted our project to Razor. The SDK works flawelessly in the Razor project, so I won't be spending any more time trying to make it work in Blazor.

Thanks for all the effort in guiding me, it's really appreciated! As far as I'm concerned this issue can be closed.

**Comment by saxx** [comment]
@mhagendoorn-9292 Thanks! Happy to hear that the Razor integration works as expected :) Don't hesitate to write mit if you have any issues. Also, we're happy to accept PRs if you're missing any features ... and yes, I know, our documentation is lacking :/

**Comment by mhagendoorn-9292** [comment]
@saxx Thanks! Is there a Slack somewhere where I should put my questions? Or should I just open new issues on GitHub?

**Comment by saxx** [comment]
@mhagendoorn-9292 Please open issues on GitHub :)
